'use strict';

const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const Category = Schema({

  title: {type: String, required: true},
  profile_image: {type: String},

  // Copied from others api YouTube or Vimeo (or just a suggestion)

  // It seems that user can subscribe to a category,
  // or may be it is just a default channel generated by the system
  // (I see that category ais just another channel created by default by the system)
  // check this https://developer.vimeo.com/api/reference/channels#add_channel_categorys

  meta: {
    videos: {type: Number, default: 0}
  },

  created: {type: Date, required: true, default: () => { return new Date() }},
  modified: Date
});

module.exports = mongoose.model('Category', Category);
